/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TugasBesar.Kelompok4.Sosmed.Componenets;

import javax.swing.JLabel;

/**
 *
 * @author sahanya
 */
public class CardPanel extends javax.swing.JPanel {

    /**
     * Creates new form CardPanel
     */
    public CardPanel() {
        initComponents();
    }

    public void setName(String TXTName) {
        this.TXTName.setText(TXTName);
    }


    public void setTitle(String text) {
        this.TXTTittle.setText(text);
    }

    public void setDesc(String text) {
        this.TXTDesc.setText(text);
    }

    public void setDate(String text) {
        this.TXTDate.setText(text);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TXTTittle = new javax.swing.JLabel();
        TXTDesc = new javax.swing.JLabel();
        TXTDate = new javax.swing.JLabel();
        TXTName = new javax.swing.JLabel();

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TXTTittle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        TXTTittle.setText("Tittle");

        TXTDesc.setText("Desc");
        TXTDesc.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        TXTDate.setText("Date");

        TXTName.setText("Nama");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TXTDesc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TXTTittle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TXTDate)
                            .addComponent(TXTName, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 9, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TXTTittle)
                .addGap(1, 1, 1)
                .addComponent(TXTName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TXTDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(TXTDate)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TXTDate;
    private javax.swing.JLabel TXTDesc;
    private javax.swing.JLabel TXTName;
    private javax.swing.JLabel TXTTittle;
    // End of variables declaration//GEN-END:variables
}
