/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TugasBesar.Kelompok4.Sosmed.Componenets;

import java.awt.Color;
import java.awt.Cursor;
import javax.swing.border.LineBorder;

/**
 *
 * @author FRZ
 */
public class CardDashboardLabel extends javax.swing.JPanel {

    public javax.swing.JLabel getjLabel1() {
        return jLabel1;
    }

    public void setText(String text) {
        this.jLabel1.setText(text);
    }

    /**
     * Creates new form CardDashboardLabel
     */
    public CardDashboardLabel() {
        initComponents();
    }

    public void isAtctive(Boolean isActive) {
        if (isActive) {

            this.setBorder(new LineBorder(new Color(255,255,255),50,true));
            jLabel1.setForeground(new Color(21,115,255));
            this.setCursor(new Cursor(0));
        }else{
            this.setBorder(new LineBorder(new Color(1,95,235),50,true));
            jLabel1.setForeground(new Color(255,255,255));
            this.setCursor(new Cursor(12));
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(21, 115, 255));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(1, 95, 235), 50, true));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setPreferredSize(new java.awt.Dimension(300, 100));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Label");
        jLabel1.setPreferredSize(new java.awt.Dimension(300, 50));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
