/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TugasBesar.Kelompok4.Sosmed.Componenets;

import TugasBesar.Kelompok4.Sosmed.Controllers.PostController;
import TugasBesar.Kelompok4.Sosmed.Views.PostDetailView;
import java.awt.Color;
import java.util.Stack;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.border.LineBorder;

/**
 *
 * @author sahanya
 */
public class CardPanel extends javax.swing.JPanel {

    PostController mode = new PostController();

    public boolean isLiked = false;
    /**
     * Creates new form CardPanel
     */
    private String id;

    public CardPanel() {
        initComponents();
        editButton.setVisible(false);
        deleteButton.setVisible(false);
        SaveButton.setVisible(false);

    }

    public void hideButton() {
        detailButton.setVisible(false);
        detailButton.setEnabled(false);

    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public void setName(String TXTName) {
        this.TXTName.setText(TXTName);
    }

    public void setTitle(String text) {
        this.TXTTittle.setText(text);
    }

    public void setDesc(String text) {
        this.TXTDesc.setText(text);
    }

    public void setDate(String text) {
        this.TXTDate.setText(text);
    }

    public void setLikeCount(String text) {
        this.TXTLike.setText(text);
    }

    public void showEditAndDeleteButton() {
editButton.setVisible(true);
deleteButton.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgorundPanel = new javax.swing.JPanel();
        TXTTittle = new javax.swing.JTextField();
        TXTDate = new javax.swing.JLabel();
        TXTName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TXTDesc = new javax.swing.JTextArea();
        likeButton = new javax.swing.JToggleButton();
        TXTLike = new javax.swing.JLabel();
        detailButton = new javax.swing.JPanel();
        detailText = new javax.swing.JLabel();
        SaveButton = new javax.swing.JPanel();
        SaveText = new javax.swing.JLabel();
        editButton = new javax.swing.JPanel();
        detailText2 = new javax.swing.JLabel();
        deleteButton = new javax.swing.JPanel();
        detailText1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1440, 284));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backgorundPanel.setBackground(new java.awt.Color(255, 255, 255));
        backgorundPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(240, 240, 240), 125, true));
        backgorundPanel.setPreferredSize(new java.awt.Dimension(1380, 250));
        backgorundPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backgorundPanelMouseClicked(evt);
            }
        });
        backgorundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TXTTittle.setEditable(false);
        TXTTittle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        TXTTittle.setText("Title");
        TXTTittle.setBorder(null);
        TXTTittle.setPreferredSize(new java.awt.Dimension(400, 30));
        TXTTittle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTTittleActionPerformed(evt);
            }
        });
        backgorundPanel.add(TXTTittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        TXTDate.setText("Date");
        backgorundPanel.add(TXTDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 210, -1, -1));

        TXTName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        TXTName.setText("Nama");
        TXTName.setPreferredSize(new java.awt.Dimension(400, 30));
        backgorundPanel.add(TXTName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1300, 90));

        TXTDesc.setEditable(false);
        TXTDesc.setColumns(20);
        TXTDesc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TXTDesc.setLineWrap(true);
        TXTDesc.setRows(3);
        jScrollPane1.setViewportView(TXTDesc);

        backgorundPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        likeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TugasBesar/Kelompok4/Sosmed/Assets/heart.png"))); // NOI18N
        likeButton.setPreferredSize(new java.awt.Dimension(50, 30));
        likeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                likeButtonMouseClicked(evt);
            }
        });
        backgorundPanel.add(likeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 205, -1, -1));

        TXTLike.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TXTLike.setText("100");
        TXTLike.setPreferredSize(new java.awt.Dimension(40, 30));
        backgorundPanel.add(TXTLike, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 205, -1, -1));

        detailButton.setBackground(new java.awt.Color(241, 241, 241));
        detailButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(21, 115, 255), 25, true));
        detailButton.setPreferredSize(new java.awt.Dimension(100, 30));
        detailButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                detailButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                detailButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                detailButtonMouseExited(evt);
            }
        });
        detailButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        detailText.setBackground(new java.awt.Color(241, 241, 241));
        detailText.setForeground(new java.awt.Color(255, 255, 255));
        detailText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        detailText.setText("Detail");
        detailText.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        detailText.setPreferredSize(new java.awt.Dimension(40, 30));
        detailText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                detailTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                detailTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                detailTextMouseExited(evt);
            }
        });
        detailButton.add(detailText, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, -1));

        backgorundPanel.add(detailButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 205, -1, -1));

        SaveButton.setBackground(new java.awt.Color(241, 241, 241));
        SaveButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 25, true));
        SaveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SaveButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SaveButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SaveButtonMouseExited(evt);
            }
        });
        SaveButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SaveText.setBackground(new java.awt.Color(241, 241, 241));
        SaveText.setForeground(new java.awt.Color(255, 255, 255));
        SaveText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SaveText.setText("Save");
        SaveText.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SaveText.setPreferredSize(new java.awt.Dimension(40, 30));
        SaveText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SaveTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SaveTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SaveTextMouseExited(evt);
            }
        });
        SaveButton.add(SaveText, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, -1));

        backgorundPanel.add(SaveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 35, -1, -1));

        editButton.setBackground(new java.awt.Color(241, 241, 241));
        editButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(243, 156, 18), 25, true));
        editButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editButtonMouseExited(evt);
            }
        });
        editButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        detailText2.setBackground(new java.awt.Color(241, 241, 241));
        detailText2.setForeground(new java.awt.Color(255, 255, 255));
        detailText2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        detailText2.setText("Edit");
        detailText2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        detailText2.setPreferredSize(new java.awt.Dimension(40, 30));
        detailText2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                detailText2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                detailText2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                detailText2MouseExited(evt);
            }
        });
        editButton.add(detailText2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, -1));

        backgorundPanel.add(editButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 35, -1, -1));

        deleteButton.setBackground(new java.awt.Color(241, 241, 241));
        deleteButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 63, 52), 25, true));
        deleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteButtonMouseExited(evt);
            }
        });
        deleteButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        detailText1.setBackground(new java.awt.Color(241, 241, 241));
        detailText1.setForeground(new java.awt.Color(255, 255, 255));
        detailText1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        detailText1.setText("Delete");
        detailText1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        detailText1.setPreferredSize(new java.awt.Dimension(40, 30));
        detailText1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                detailText1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                detailText1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                detailText1MouseExited(evt);
            }
        });
        deleteButton.add(detailText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, -1));

        backgorundPanel.add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 35, -1, -1));

        add(backgorundPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void likeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_likeButtonMouseClicked

// TODO add your handling code here:
        isLiked = !isLiked;
        Integer GetTLike = Integer.parseInt(TXTLike.getText());
        mode.Liker(GetTLike, isLiked, id);

        Stack<String> PostUpdated = mode.getDetail(id);
        TXTLike.setText(PostUpdated.get(5));
    }//GEN-LAST:event_likeButtonMouseClicked

    private void backgorundPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgorundPanelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_backgorundPanelMouseClicked

    private void detailButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_detailButtonMouseExited
        // TODO add your handling code here:
        detailButton.setBorder(new LineBorder(new Color(21, 115, 255), 25, true));
    }//GEN-LAST:event_detailButtonMouseExited

    private void detailButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_detailButtonMouseEntered
        // TODO add your handling code here:
        detailButton.setBorder(new LineBorder(new Color(1, 95, 235), 25, true));
    }//GEN-LAST:event_detailButtonMouseEntered

    private void detailButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_detailButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_detailButtonMouseClicked

    private void detailTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_detailTextMouseExited
        // TODO add your handling code here:
        detailButton.setBorder(new LineBorder(new Color(21, 115, 255), 25, true));
    }//GEN-LAST:event_detailTextMouseExited

    private void detailTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_detailTextMouseEntered
        // TODO add your handling code here:
        detailButton.setBorder(new LineBorder(new Color(1, 95, 235), 25, true));
    }//GEN-LAST:event_detailTextMouseEntered

    private void detailTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_detailTextMouseClicked
        // TODO add your handling code here:
        System.out.println(this.getId());
        PostDetailView detail = new PostDetailView(this.getId());
        detail.setVisible(true);
    }//GEN-LAST:event_detailTextMouseClicked

    private void detailText1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_detailText1MouseClicked
        // TODO add your handling code here:
        mode.DeletePost(id);
        
    }//GEN-LAST:event_detailText1MouseClicked

    private void detailText1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_detailText1MouseEntered
        // TODO add your handling code here:
        deleteButton.setBorder(new LineBorder(new Color(245, 53, 42), 25, true));
    }//GEN-LAST:event_detailText1MouseEntered

    private void detailText1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_detailText1MouseExited
        // TODO add your handling code here:
        deleteButton.setBorder(new LineBorder(new Color(255, 63, 52), 25, true));
    }//GEN-LAST:event_detailText1MouseExited

    private void deleteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteButtonMouseClicked

    private void deleteButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteButtonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteButtonMouseEntered

    private void deleteButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteButtonMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteButtonMouseExited

    private void detailText2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_detailText2MouseClicked
        // TODO add your handling code here:
        TXTTittle.setEditable(true);
        TXTDesc.setEditable(true);
        SaveButton.setVisible(true);
        editButton.setVisible(false);
    }//GEN-LAST:event_detailText2MouseClicked

    private void detailText2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_detailText2MouseEntered
        // TODO add your handling code here:
        editButton.setBorder(new LineBorder(new Color(233, 146, 8), 25, true));
    }//GEN-LAST:event_detailText2MouseEntered

    private void detailText2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_detailText2MouseExited
        // TODO add your handling code here:
        editButton.setBorder(new LineBorder(new Color(243, 156, 18), 25, true));
    }//GEN-LAST:event_detailText2MouseExited

    private void editButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_editButtonMouseClicked

    private void editButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editButtonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_editButtonMouseEntered

    private void editButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editButtonMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_editButtonMouseExited

    private void TXTTittleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTTittleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTTittleActionPerformed

    private void SaveTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveTextMouseClicked
        // TODO add your handling code here:
        String[] inputs = {TXTName.getText(),TXTDesc.getText(),id};
        
        mode.update(inputs);
        TXTDesc.setEditable(false);
        TXTTittle.setEditable(false);
        SaveButton.setVisible(false);
        editButton.setVisible(true);
    }//GEN-LAST:event_SaveTextMouseClicked

    private void SaveTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveTextMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_SaveTextMouseEntered

    private void SaveTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveTextMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_SaveTextMouseExited

    private void SaveButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_SaveButtonMouseClicked

    private void SaveButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveButtonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_SaveButtonMouseEntered

    private void SaveButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveButtonMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_SaveButtonMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SaveButton;
    private javax.swing.JLabel SaveText;
    private javax.swing.JLabel TXTDate;
    private javax.swing.JTextArea TXTDesc;
    private javax.swing.JLabel TXTLike;
    private javax.swing.JLabel TXTName;
    private javax.swing.JTextField TXTTittle;
    private javax.swing.JPanel backgorundPanel;
    private javax.swing.JPanel deleteButton;
    private javax.swing.JPanel detailButton;
    private javax.swing.JLabel detailText;
    private javax.swing.JLabel detailText1;
    private javax.swing.JLabel detailText2;
    private javax.swing.JPanel editButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton likeButton;
    // End of variables declaration//GEN-END:variables
}
