/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TugasBesar.Kelompok4.Sosmed.Componenets;

import TugasBesar.Kelompok4.Sosmed.Controllers.PostController;
import java.awt.Color;
import javax.swing.border.LineBorder;

/**
 *
 * @author FRZ
 */
public class CreatePostPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreatePostPanel
     */
           PostController button=new PostController();

    public CreatePostPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        namaPanel = new javax.swing.JPanel();
        nama = new javax.swing.JLabel();
        backgroundTitle = new javax.swing.JPanel();
        titleField = new javax.swing.JTextField();
        backgroundPost = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        postField = new javax.swing.JTextArea();
        postButton = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1440, 284));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backgroundPanel.setBackground(new java.awt.Color(255, 255, 255));
        backgroundPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(240, 240, 240), 125, true));
        backgroundPanel.setPreferredSize(new java.awt.Dimension(1400, 250));
        backgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        namaPanel.setBackground(new java.awt.Color(241, 241, 241));
        namaPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 50, true));
        namaPanel.setPreferredSize(new java.awt.Dimension(300, 50));
        namaPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nama.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        nama.setText("Nama");
        nama.setPreferredSize(new java.awt.Dimension(260, 50));
        namaPanel.add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        backgroundPanel.add(namaPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        backgroundTitle.setBackground(new java.awt.Color(241, 241, 241));
        backgroundTitle.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 50, true));
        backgroundTitle.setPreferredSize(new java.awt.Dimension(300, 50));
        backgroundTitle.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleField.setText("Title");
        titleField.setBorder(null);
        titleField.setPreferredSize(new java.awt.Dimension(260, 50));
        titleField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleFieldActionPerformed(evt);
            }
        });
        backgroundTitle.add(titleField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        backgroundPanel.add(backgroundTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        backgroundPost.setBackground(new java.awt.Color(241, 241, 241));
        backgroundPost.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 50, true));
        backgroundPost.setPreferredSize(new java.awt.Dimension(1360, 100));
        backgroundPost.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        postField.setColumns(20);
        postField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        postField.setRows(5);
        jScrollPane1.setViewportView(postField);

        backgroundPost.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 1320, 100));

        backgroundPanel.add(backgroundPost, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        postButton.setBackground(new java.awt.Color(241, 241, 241));
        postButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(21, 115, 255), 25, true));
        postButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        postButton.setPreferredSize(new java.awt.Dimension(150, 40));
        postButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                postButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                postButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                postButtonMouseExited(evt);
            }
        });
        postButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Post");
        jLabel2.setPreferredSize(new java.awt.Dimension(150, 40));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        postButton.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        backgroundPanel.add(postButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 200, -1, -1));

        add(backgroundPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 17, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void postButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_postButtonMouseEntered
        // TODO add your handling code here:
        postButton.setBorder(new LineBorder(new Color(1,95,235),25,true));
    }//GEN-LAST:event_postButtonMouseEntered

    private void postButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_postButtonMouseExited
        // TODO add your handling code here:
        postButton.setBorder(new LineBorder(new Color(21,115,255),25,true));
    }//GEN-LAST:event_postButtonMouseExited

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
          button.ForSend(titleField.getText(),postField.getText());
        System.out.println("button telah di klik");
    }//GEN-LAST:event_jLabel2MouseClicked

    private void postButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_postButtonMouseClicked
    
        // TODO add your handling code here:
    }//GEN-LAST:event_postButtonMouseClicked

    private void titleFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titleFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JPanel backgroundPost;
    private javax.swing.JPanel backgroundTitle;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nama;
    private javax.swing.JPanel namaPanel;
    private javax.swing.JPanel postButton;
    private javax.swing.JTextArea postField;
    private javax.swing.JTextField titleField;
    // End of variables declaration//GEN-END:variables
}
