/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TugasBesar.Kelompok4.Sosmed.Views;

//import TugasBesar.Kelompok4.Sosmed.Componenets.CardComponent;
//import TugasBesar.Kelompok4.Sosmed.Componenets.CardPanel;
import TugasBesar.Kelompok4.Sosmed.Controllers.AuthController;
//import java.awt.BorderLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.AbstractBorder;
import javax.swing.border.CompoundBorder;

/**
 *
 * @author sahanya
 */
public class LoginView extends javax.swing.JFrame {

    /**
     * Creates new form LoginView
     */
    AuthController controller;

    public LoginView() {
        initComponents();
        controller=new AuthController();
        this.setExtendedState(JFrame.MAXIMIZED_HORIZ);
        this.setResizable(false);
        loginButton.setText("Login");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        forgetPassword = new javax.swing.JLabel();
        loginButton = new TugasBesar.Kelompok4.Sosmed.Componenets.ButtonPanel();
        registerLabel = new javax.swing.JLabel();
        register = new javax.swing.JLabel();
        copyright = new javax.swing.JLabel();
        aboutUs = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backgroundPanel.setBackground(new java.awt.Color(21, 115, 255));
        backgroundPanel.setPreferredSize(new java.awt.Dimension(700, 760));
        backgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));
        mainPanel.setForeground(new java.awt.Color(255, 255, 255));
        mainPanel.setPreferredSize(new java.awt.Dimension(500, 660));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Login");
        Title.setPreferredSize(new java.awt.Dimension(100, 50));
        mainPanel.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, -1));

        usernameLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        usernameLabel.setText("Username");
        usernameLabel.setPreferredSize(new java.awt.Dimension(200, 30));
        mainPanel.add(usernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        passwordLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        passwordLabel.setText("Password");
        passwordLabel.setPreferredSize(new java.awt.Dimension(200, 30));
        mainPanel.add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        usernameField.setToolTipText("");
        usernameField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(21, 115, 255), 2, true));
        usernameField.setPreferredSize(new java.awt.Dimension(400, 50));
        usernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldActionPerformed(evt);
            }
        });
        mainPanel.add(usernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));
        usernameField.getAccessibleContext().setAccessibleDescription("jnmk,");

        passwordField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(21, 115, 255), 2, true));
        passwordField.setPreferredSize(new java.awt.Dimension(400, 50));
        mainPanel.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        forgetPassword.setForeground(new java.awt.Color(21, 115, 255));
        forgetPassword.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        forgetPassword.setText("Lupa Password?");
        forgetPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        forgetPassword.setPreferredSize(new java.awt.Dimension(150, 30));
        forgetPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgetPasswordMouseClicked(evt);
            }
        });
        mainPanel.add(forgetPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, -1, -1));

        loginButton.setForeground(new java.awt.Color(255, 255, 255));
        loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginButtonMouseClicked(evt);
            }
        });
        mainPanel.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, -1, -1));

        registerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registerLabel.setText("Belum punya akun?");
        registerLabel.setPreferredSize(new java.awt.Dimension(300, 30));
        mainPanel.add(registerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 510, -1, -1));

        register.setForeground(new java.awt.Color(21, 115, 255));
        register.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        register.setText("Daftar Sekarang!");
        register.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        register.setPreferredSize(new java.awt.Dimension(300, 30));
        register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerMouseClicked(evt);
            }
        });
        mainPanel.add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 540, -1, -1));

        copyright.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        copyright.setText("Copyright (c) 2022, FSociety");
        copyright.setPreferredSize(new java.awt.Dimension(300, 30));
        mainPanel.add(copyright, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 590, -1, -1));

        aboutUs.setForeground(new java.awt.Color(21, 115, 255));
        aboutUs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aboutUs.setText("About Us");
        aboutUs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aboutUs.setPreferredSize(new java.awt.Dimension(300, 30));
        mainPanel.add(aboutUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 620, -1, -1));

        backgroundPanel.add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        getContentPane().add(backgroundPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldActionPerformed

    private void registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerMouseClicked
        new RegisterView().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_registerMouseClicked

    private void loginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMouseClicked
        // TODO add your handling code here:
        String roleLogged = controller.login(usernameField.getText(), passwordField.getText());
        if ("admin".equals(roleLogged)){
            this.setVisible(false);
            new UserManagement().setVisible(true);
        }else if("user".equals(roleLogged)){
            this.setVisible(false);
            new HomeView().setVisible(true);
            
        }
    }//GEN-LAST:event_loginButtonMouseClicked

    private void forgetPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgetPasswordMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new ForgetPasswordView().setVisible(true);
    }//GEN-LAST:event_forgetPasswordMouseClicked
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JLabel aboutUs;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JLabel copyright;
    private javax.swing.JLabel forgetPassword;
    private TugasBesar.Kelompok4.Sosmed.Componenets.ButtonPanel loginButton;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel register;
    private javax.swing.JLabel registerLabel;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
