/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package TugasBesar.Kelompok4.Sosmed.Views;

import TugasBesar.Kelompok4.Sosmed.Controllers.AuthController;

/**
 *
 * @author FRZ
 */
public class RegisterView extends javax.swing.JFrame {

    /** Creates new form RegisterView */
    AuthController controller;
    public RegisterView() {
        initComponents();
        this.setResizable(false);
        registerButton.setText("Register");
        controller = new AuthController();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        namaLabel = new javax.swing.JLabel();
        rePasswordLabel = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        rePasswordField = new javax.swing.JPasswordField();
        registerButton = new TugasBesar.Kelompok4.Sosmed.Componenets.ButtonPanel();
        loginLabel = new javax.swing.JLabel();
        login = new javax.swing.JLabel();
        copyright = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        passwordLabel = new javax.swing.JLabel();
        namaField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backgroundPanel.setBackground(new java.awt.Color(21, 115, 255));
        backgroundPanel.setPreferredSize(new java.awt.Dimension(700, 760));
        backgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 10, true));
        mainPanel.setForeground(new java.awt.Color(255, 255, 255));
        mainPanel.setPreferredSize(new java.awt.Dimension(500, 660));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Sign-up");
        Title.setPreferredSize(new java.awt.Dimension(200, 50));
        mainPanel.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));

        namaLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        namaLabel.setText("Nama");
        namaLabel.setPreferredSize(new java.awt.Dimension(200, 30));
        mainPanel.add(namaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        rePasswordLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        rePasswordLabel.setText("Re-Password");
        rePasswordLabel.setPreferredSize(new java.awt.Dimension(200, 30));
        mainPanel.add(rePasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 190, -1));

        usernameField.setToolTipText("");
        usernameField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(21, 115, 255), 2, true));
        usernameField.setPreferredSize(new java.awt.Dimension(400, 50));
        usernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldActionPerformed(evt);
            }
        });
        mainPanel.add(usernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        rePasswordField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(21, 115, 255), 2, true));
        rePasswordField.setPreferredSize(new java.awt.Dimension(190, 50));
        rePasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rePasswordFieldActionPerformed(evt);
            }
        });
        mainPanel.add(rePasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 440, -1, -1));

        registerButton.setForeground(new java.awt.Color(255, 255, 255));
        registerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerButtonMouseClicked(evt);
            }
        });
        mainPanel.add(registerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, -1, -1));

        loginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginLabel.setText("Sudah mempunyai akun?");
        loginLabel.setPreferredSize(new java.awt.Dimension(300, 30));
        mainPanel.add(loginLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 580, 190, -1));

        login.setForeground(new java.awt.Color(21, 115, 255));
        login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login.setText("Login");
        login.setPreferredSize(new java.awt.Dimension(300, 30));
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
        });
        mainPanel.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 580, 50, -1));

        copyright.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        copyright.setText("Copyright (c) 2022, FSociety");
        copyright.setPreferredSize(new java.awt.Dimension(300, 30));
        mainPanel.add(copyright, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 620, -1, -1));

        usernameLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        usernameLabel.setText("Username");
        usernameLabel.setPreferredSize(new java.awt.Dimension(200, 30));
        mainPanel.add(usernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        passwordField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(21, 115, 255), 2, true));
        passwordField.setPreferredSize(new java.awt.Dimension(190, 50));
        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });
        mainPanel.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, -1, -1));

        passwordLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        passwordLabel.setText("Password");
        passwordLabel.setPreferredSize(new java.awt.Dimension(190, 30));
        mainPanel.add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, -1));

        namaField.setToolTipText("");
        namaField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(21, 115, 255), 2, true));
        namaField.setPreferredSize(new java.awt.Dimension(400, 50));
        namaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaFieldActionPerformed(evt);
            }
        });
        mainPanel.add(namaField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        backgroundPanel.add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        getContentPane().add(backgroundPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldActionPerformed

    private void rePasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rePasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rePasswordFieldActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked
        new LoginView().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_loginMouseClicked

    private void registerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerButtonMouseClicked
        // TODO add your handling code here:
        String[] inputs= {usernameField.getText(),usernameField.getText(),passwordField.getText(),rePasswordField.getText()};
        if(controller.register(inputs)){
            new LoginView().setVisible(true);
            this.setVisible(false);
        }
        
        
    }//GEN-LAST:event_registerButtonMouseClicked

    private void namaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JLabel copyright;
    private javax.swing.JLabel login;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField namaField;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField rePasswordField;
    private javax.swing.JLabel rePasswordLabel;
    private TugasBesar.Kelompok4.Sosmed.Componenets.ButtonPanel registerButton;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables

}
